---
abstract: 'Generate Perl GUI code from wxFormBuilder .fbp files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0.80
  Test::LongString: 0.13
  Test::More: 0.47
  Test::NoWarnings: 0.084
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: FBP::Perl
name: FBP-Perl
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::Dumper: 2.122
  FBP: 0.25
  Mouse: 0.61
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/FBP-Perl
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/FBP-Perl
version: 0.32
