---
abstract: 'Generate Perl GUI code from wxFormBuilder .fbp files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  File::Spec: 0.80
  Test::LongString: 0.13
  Test::More: 0.47
  Test::NoWarnings: 0.084
  Wx: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: FBP::Perl
name: FBP-Perl
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  FBP: 0.39
  Params::Util: 1.00
  Scalar::Util: 1.19
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/FBP-Perl
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/FBP-Perl
version: 0.74
